In [21]:
import theano
from theano import tensor as T, function

import numpy as np

In [22]:
X = T.matrix('x')
Y = X ** 2
Z = T.grad(Y.sum(),X)
F = function([X],[Y,Z])

In [23]:
x = np.ones((2,2)) * 3
y,z = F(x)

In [24]:
print(x)
print('-' * 36)
print(y)
print('-' * 36)
print(z)

[[3. 3.]
 [3. 3.]]
------------------------------------
[[9. 9.]
 [9. 9.]]
------------------------------------
[[6. 6.]
 [6. 6.]]
